CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  is_admin BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE UNIQUE INDEX IF NOT EXISTS users_username_casefold_index ON users (lower(username));

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_user_id_index ON sessions(user_id);
CREATE INDEX IF NOT EXISTS sessions_expires_at_index ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS problems (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  input_format TEXT NOT NULL,
  output_format TEXT NOT NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('Easy', 'Medium', 'Hard')),
  tags_json JSONB NOT NULL,
  languages_json JSONB NOT NULL,
  examples_json JSONB NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0)
);

CREATE TABLE IF NOT EXISTS problem_tests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  problem_id TEXT NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
  input TEXT NOT NULL,
  expected_output TEXT NOT NULL,
  position BIGINT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
  UNIQUE(problem_id, position)
);
CREATE INDEX IF NOT EXISTS problem_tests_judge_index ON problem_tests(problem_id, enabled, position);

CREATE TABLE IF NOT EXISTS submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  problem_id TEXT NOT NULL,
  language TEXT NOT NULL,
  source_code TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('queued', 'running', 'completed', 'failed')),
  verdict TEXT CHECK (verdict IS NULL OR verdict IN
    ('Accepted', 'Wrong Answer', 'Runtime Error', 'Time Limit Exceeded')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  completed_at TIMESTAMPTZ,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  error_type TEXT,
  retry_of BIGINT REFERENCES submissions(id) ON DELETE SET NULL,
  CHECK (
    (status IN ('queued', 'running') AND verdict IS NULL AND completed_at IS NULL) OR
    (status = 'completed' AND verdict IS NOT NULL AND completed_at IS NOT NULL) OR
    (status = 'failed' AND verdict IS NULL AND completed_at IS NOT NULL)
  )
);
CREATE INDEX IF NOT EXISTS submissions_user_problem_created_index
  ON submissions(user_id, problem_id, created_at DESC);
CREATE INDEX IF NOT EXISTS submissions_queue_index ON submissions(status, id);
CREATE UNIQUE INDEX IF NOT EXISTS submissions_retry_once_index
  ON submissions(retry_of) WHERE retry_of IS NOT NULL;
CREATE INDEX IF NOT EXISTS submissions_admin_filter_index
  ON submissions(status, error_type, language, problem_id, user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS admin_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  details_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX IF NOT EXISTS admin_audit_created_index ON admin_audit_log(created_at DESC, id DESC);
